title: DSGN
description: "Paul Anthony Webb does webb design. I mean, web. I was literally made for this."
url: "http://dsgn.io"
markdown: rdiscount

paginate: 5
permalink: /:categories/:title

exclude:
  - Capfile
  - config
  - style.scss

rdiscount:
  extensions:
    - smart

sass:
  style: compressed