// Toe.js 3.0.6
// Damien Antipa (https://github.com/dantipa/toe.js)

!function(t,n){function e(n,e,o,i){t.each(c,function(t,a){a[n].call(this,e,o,i)})}function o(t){var n=u.Event(t);r=u.State(n),e("touchstart",t,r,n)}function i(t){if(r){var n=u.Event(t);r.move.push(n),e("touchmove",t,r,n)}}function a(t){var n=u.Event(t);r.end=n,e("touchend",t,r,n)}var r,c={},u={active:!1,on:function(){t(document).on("touchstart MSPointerDown pointerdown",o).on("touchmove MSPointerMove MSPointerHover pointermove",i).on("touchend touchcancel MSPointerUp MSPointerCancel pointerup pointercancel",a),u.active=!0},off:function(){t(document).off("touchstart MSPointerDown pointerdown",o).off("touchmove MSPointerMove MSPointerHover pointermove",i).off("touchend touchcancel MSPointerUp MSPointerCancel pointerup pointercancel",a),u.active=!1},track:function(t,n){c[t]=n},addEventParam:function(n,e){var o=t(n.target),i=o.offset(),a={pageX:n.point[0].x,pageY:n.point[0].y,offsetX:i.left-n.point[0].x,offsetY:i.top-n.point[0].y};return t.extend(a,e)},Event:function(n){var e={type:n.type,timestamp:(new Date).getTime(),target:n.target,point:[]},o=[];return n.type.indexOf("touch")>-1?o=n.changedTouches||n.originalEvent.changedTouches||n.touches||n.originalEvent.touches:n.type.match(/.*?pointer.*?/i)&&(o=[n.originalEvent]),t.each(o,function(t,n){e.point.push({x:n.pageX,y:n.pageY})}),e},State:function(t){t.point[0];return{start:t,move:[],end:null}},calc:{getDuration:function(t,n){return n.timestamp-t.timestamp},getDistance:function(t,n){return Math.sqrt(Math.pow(n.x-t.x,2)+Math.pow(n.y-t.y,2))},getAngle:function(t,n){return 180*Math.atan2(n.y-t.y,n.x-t.x)/Math.PI},getDirection:function(t){return-45>t&&t>-135?"up":t>=-45&&45>=t?"right":t>=45&&135>t?"down":t>=135||-135>=t?"left":"unknown"},getScale:function(t,n){var e=t.point,o=n.point;return 2===e.length&&2===o.length?(Math.sqrt(Math.pow(o[0].x-o[1].x,2)+Math.pow(o[0].y-o[1].y,2))/Math.sqrt(Math.pow(e[0].x-e[1].x,2)+Math.pow(e[0].y-e[1].y,2))).toFixed(2):0},getRotation:function(t,n){var e=t.point,o=n.point;return 2===e.length&&2===o.length?(180*Math.atan2(o[0].y-o[1].y,o[0].x-o[1].x)/Math.PI-180*Math.atan2(e[0].y-e[1].y,e[0].x-e[1].x)/Math.PI).toFixed(2):0}}};u.on(),t.toe=u}(jQuery,this);

// Swipe
!function(t,n){var i="swipe",e={distance:100,duration:1200,direction:"all"};n.track(i,{touchstart:function(t,n,e){n[i]={finger:e.point.length}},touchmove:function(t,n,e){n[i].finger=e.point.length>n[i].finger?e.point.length:n[i].finger},touchend:function(a,r,c){var o,g,d=t.extend(e,a.data);o=n.calc.getDuration(r.start,c),g=n.calc.getDistance(r.start.point[0],c.point[0]),o<d.duration&&g>d.distance&&(r[i].angle=n.calc.getAngle(r.start.point[0],c.point[0]),r[i].direction=n.calc.getDirection(r[i].angle),r[i].distance=g,("all"===d.direction||r[i].direction===d.direction)&&t(a.target).trigger(t.Event(i,n.addEventParam(r.start,r[i]))))}})}(jQuery,jQuery.toe,this);

// Tap
!function(t,n){var e=document.documentElement.clientWidth,i=document.documentElement.clientHeight,r=Math.sqrt(e*i),a=.02*r,c="tap",o={distance:a,duration:300,finger:1};n.track(c,{touchstart:function(t,n,e){n[c]={finger:e.point.length}},touchmove:function(t,n,e){n[c].finger=e.point.length>n[c].finger?e.point.length:n[c].finger},touchend:function(e,i,r){var a,g,u=t.extend(o,e.data);a=n.calc.getDuration(i.start,r),g=n.calc.getDistance(i.start.point[0],r.point[0]),a<u.duration&&g<u.distance&&i[c].finger===u.finger&&t(e.target).trigger(t.Event(c,n.addEventParam(i.start,i[c])))}})}(jQuery,jQuery.toe,this);

// Tap/Hold
!function(t,n){var e,i,a="taphold",r={distance:20,duration:500,finger:1};n.track(a,{touchstart:function(o,c,u){var g=t.extend(r,o.data);i=!1,c[a]={finger:u.point.length},clearTimeout(e),e=setTimeout(function(){!i&&n.active&&c[a].finger===g.finger&&t(o.target).trigger(t.Event(a,n.addEventParam(u,c[a])))},g.duration)},touchmove:function(e,o,c){var u,g=t.extend(r,e.data);o[a].finger=c.point.length>o[a].finger?c.point.length:o[a].finger,u=n.calc.getDistance(o.start.point[0],c.point[0]),u>g.distance&&(i=!0)},touchend:function(){i=!0,clearTimeout(e)}})}(jQuery,jQuery.toe,this);

// Transform
!function(t,e){var a,n="transform",r={scale:.1,rotation:15};e.track(n,{touchstart:function(t,e,r){a=!1,e[n]={start:r,move:[]}},touchmove:function(o,c,s){var i=t.extend(r,o.data);2===s.point.length&&(c[n].move.push(s),2!==c[n].start.point.length&&2===s.point.length&&(c[n].start=t.extend({},s)),c[n].rotation=e.calc.getRotation(c[n].start,s),c[n].scale=e.calc.getScale(c[n].start,s),(Math.abs(1-c[n].scale)>i.scale||Math.abs(c[n].rotation)>i.rotation)&&(a||(t(o.target).trigger(t.Event("transformstart",c[n])),a=!0),t(o.target).trigger(t.Event("transform",c[n]))))},touchend:function(r,o,c){a&&(a=!1,2!==c.point.length&&(o.end=t.extend({},o[n].move[o[n].move.length-1])),o[n].rotation=e.calc.getRotation(o[n].start,o.end),o[n].scale=e.calc.getScale(o[n].start,o.end),t(r.target).trigger(t.Event("transformend",o[n])))}})}(jQuery,jQuery.toe,this);